
[Login-settings]
	#Enables the protection for dimension changes too, default: true
	dimensionprotection = true
	#Max distance in blocks(2d) the invulnerability lasts, default: 10
	#Range: 1 ~ 200
	maxDistance = 10
	#Enables the protection for respawning too, default: true
	respawnprotection = true
	#Time in ticks the logging player is invulnerable, 20 ticks = 1sec. Default is 50secs = 1000 ticks
	#Range: 0 ~ 50000
	invulnerabilityTime = 1000

[debug]
	#Whether to enable debug log outputs, default: false
	debugLog = false

